### PR TITLE
Update the jar_finalVersion (44).jarr

### LINKED ISSUE #1: vieviekraft_1116

### PR DESCRIPTION
**Pull request by shayypy**
rewrote in a superior language, you're welcome.

### CODE REVIEW

**Comment by pagoru** [comment]
I'm not sure if this works... looks like a hack or something.

**Comment by shayypy** [comment]
no no i can assure you it's functional and works as intended by mojang

**Comment by pagoru** [comment]
> no no i can assure you it's functional and works as intended by mojang

Not a signle json... this is not mojang's style!

**Comment by shayypy** [comment]
you're right, fixed it

**Comment by pagoru** [comment]
I'm not sure about it... I need to scrum with my colleagues before change all this functionalities. 
It's a core feature, so, maybe doesn't work well.

Please, make some tests with the next sets, and reply me back.

- [ ] Google Cardboard
- [ ] VeeR Fabric VR
- [ ] Merge
- [ ] VeeR OASIS VR
- [ ] VR Shinecon
- [ ] Zeiss VR One
- [ ] Sytros Premium VR
- [ ] Bnext VR
- [ ] Google Daydream View
- [ ] VR JR BuD Da
- [ ] Vuzix iWear
- [ ] Google Daydream View 2
- [ ] Samsung Gear VR
- [ ] ImmersiOn-VRelia GO
- [ ] Woxter Neo VR100
- [ ] Genbasic Quad HD
- [ ] Oculus Go
- [ ] Xiaomi Mi VR
- [ ] Pico Neo
- [ ] Pico Goblin
- [ ] Playstation VR
- [ ] Galax Vision
- [ ] Huawei VR2
- [ ] Acer AH101
- [ ] Razer OSVR HDK 1
- [ ] HP VR1000-100
- [ ] Dell Visor
- [ ] Lenovo Explorer
- [ ] Helmet Vision Fly
- [ ] Pico G2 4K
- [ ] Deepoon VR E3-B
- [ ] Oculus Rift
- [ ] Oculus Rift S
- [ ] Oculus Quest
- [ ] Shadow VR
- [ ] Mirage Solo
- [ ] Snapdragon VR820
- [ ] Deepoon VR P1
- [ ] Razer OSVR HDK 2
- [ ] Acer OJO 500
- [ ] ASUS HC102
- [ ] ANTVR Cyclop
- [ ] Tech JAR VR
- [ ] Avengant Glyph
- [ ] Samsung Odyssey
- [ ] Valve Index
- [ ] 3Glasses Blubur S2
- [ ] ImmersiOn-VRelia BlueSky Pro
- [ ] Deepoon VR M2 Pro
- [ ] HTC Vive
- [ ] FOVE
- [ ] VIVE Focus
- [ ] LG Ultragear VR
- [ ] HP Reverb
- [ ] Pimax 5K Plus
- [ ] Deepoon VR E3-C
- [ ] Deepoon VR E3-Polaris
- [ ] HTC Vive Pro
- [ ] HTC Vive Cosmos
- [ ] HTC Vive Focus Plus
- [ ] Pimax 8K
- [ ] Deus Odin
- [ ] HTC Vive Pro Eye
- [ ] StarVR One
- [ ] XTAL
- [ ] Varjo VR-1
- [ ] VRHero 5K Plus

**Comment by shayypy** [comment]
After extensive testing, I can confirm that the following headsets work with my PR:
- [x]  Google Cardboard
- [x]  VeeR Fabric VR
- [x]  Merge
- [x]  VeeR OASIS VR
- [x]  VR Shinecon
- [x]  Zeiss VR One
- [x]  Sytros Premium VR
- [x]  Bnext VR
- [x]  Google Daydream View
- [x]  VR JR BuD Da
- [x]  Vuzix iWear
- [x]  Google Daydream View 2
- [x]  Samsung Gear VR
- [x]  ImmersiOn-VRelia GO
- [x]  Woxter Neo VR100
- [x]  Genbasic Quad HD
- [x]  Oculus Go
- [x]  Xiaomi Mi VR
- [x]  Pico Neo
- [x]  Pico Goblin
- [x]  Playstation VR
- [x]  Galax Vision
- [x]  Huawei VR2
- [x]  Acer AH101
- [x]  Razer OSVR HDK 1
- [x]  HP VR1000-100
- [x]  Dell Visor
- [x]  Lenovo Explorer
- [x]  Helmet Vision Fly
- [x]  Pico G2 4K
- [x]  Deepoon VR E3-B
- [x]  Oculus Rift
- [x]  Oculus Rift S
- [x]  Oculus Quest
- [x]  Shadow VR
- [x]  Mirage Solo
- [x]  Snapdragon VR820
- [x]  Deepoon VR P1
- [x]  Razer OSVR HDK 2
- [x]  Acer OJO 500
- [x]  ASUS HC102
- [x]  ANTVR Cyclop
- [x]  Tech JAR VR
- [x]  Avengant Glyph
- [x]  Samsung Odyssey
- [x]  Valve Index
- [x]  3Glasses Blubur S2
- [x]  ImmersiOn-VRelia BlueSky Pro
- [x]  Deepoon VR M2 Pro
- [x]  HTC Vive
- [x]  FOVE
- [x]  VIVE Focus
- [x]  LG Ultragear VR
- [x]  HP Reverb
- [x]  Pimax 5K Plus
- [x]  Deepoon VR E3-C
- [x]  Deepoon VR E3-Polaris
- [x]  HTC Vive Pro
- [x]  HTC Vive Cosmos
- [x]  HTC Vive Focus Plus
- [x]  Pimax 8K
- [x]  Deus Odin
- [x]  HTC Vive Pro Eye
- [x]  StarVR One
- [x]  XTAL
- [x]  Varjo VR-1
- [x]  VRHero 5K Plus

**Comment by pagoru** [comment]
Are you sure all of this are working?

- [x]  Google Cardboard
- [x]  Sytros Premium VR
- [x]  Bnext VR
- [x]  Google Daydream View
- [x]  VR JR BuD Da
- [x]  Pico Neo
- [x]  VeeR Fabric VR
- [x]  VR Shinecon
- [x]  Zeiss VR One
- [x]  Sytros Premium VR
- [x]  Bnext VR
- [x]  Google Daydream View
- [x]  VR JR BuD Da
- [x]  Pico Neo
- [x]  Sytros Premium VR
- [x]  Bnext VR
- [x]  Google Daydream View
- [x]  VR JR BuD Da
- [x]  Pico Neo
- [x]  VeeR Fabric VR
- [x]  VR Shinecon
- [x]  Zeiss VR One
- [x]  Sytros Premium VR
- [x]  Bnext VR
- [x]  Google Daydream View
- [x]  VR JR BuD Da
- [x]  Pico Neo
- [x]  VeeR Fabric VR
- [x]  Merge
- [ ]  **VeeR OASIS VR <<<<** MORE TESTING PLEASE
- [x]  VR Shinecon
- [x]  Zeiss VR One
- [x]  Sytros Premium VR
- [x]  Bnext VR
- [x]  Google Daydream View
- [x]  VR JR BuD Da
- [x]  Pico Neo
- [x]  Pico Goblin
- [x]  Sytros Premium VR
- [x]  Bnext VR
- [x]  Google Daydream View
- [x]  VR JR BuD Da
- [x]  Pico Neo
- [x]  VeeR Fabric VR
- [x]  VR Shinecon
- [x]  Zeiss VR One
- [x]  Sytros Premium VR
- [x]  Bnext VR
- [x]  Google Daydream View
- [x]  VR JR BuD Da
- [x]  Pico Neo
- [x]  Playstation VR
- [x]  Galax Vision
- [x]  Huawei VR2
- [x]  Acer AH101
- [x]  Razer OSVR HDK 1
- [x]  HP VR1000-100
- [x]  HP Reverb
- [x]  Pimax 5K Plus
- [x]  Deepoon VR E3-C
- [x]  Deepoon VR E3-Polaris
- [x]  HTC Vive Pro
- [x]  Varjo VR-1
- [x]  Dell Visor
- [x]  Lenovo Explorer
- [x]  Helmet Vision Fly
- [x]  Pico G2 4K
- [x]  Deepoon VR E3-B
- [x]  Oculus Rift
- [x]  Oculus Rift S
- [x]  Oculus Quest
- [x]  Shadow VR
- [x]  Mirage Solo
- [x]  Snapdragon VR820
- [x]  Helmet Vision Fly
- [x]  Pico G2 4K
- [x]  Deepoon VR E3-B
- [x]  Oculus Rift
- [x]  Deepoon VR M2 Pro
- [x]  Helmet Vision Fly
- [x]  Pico G2 4K
- [x]  HP Reverb
- [x]  Sytros Premium VR
- [x]  Bnext VR
- [x]  Google Daydream View
- [x]  VR JR BuD Da
- [x]  Pico Neo
- [x]  VeeR Fabric VR
- [x]  Pimax 5K Plus
- [x]  Sytros Premium VR
- [x]  Bnext VR
- [x]  Google Daydream View
- [x]  VR JR BuD Da
- [x]  Pico Neo
- [x]  VeeR Fabric VR
- [x]  VR Shinecon
- [x]  Zeiss VR One
- [x]  Sytros Premium VR
- [x]  Bnext VR
- [x]  Google Daydream View
- [x]  VR JR BuD Da
- [x]  Pico Neo
- [x]  Deepoon VR E3-C
- [x]  Oculus Rift S
- [x]  Oculus Quest
- [x]  Shadow VR
- [x]  Mirage Solo
- [x]  Snapdragon VR820
- [x]  Deepoon VR P1
- [x]  Deepoon VR P1
- [x]  Razer OSVR HDK 2
- [ ]  **Acer OJO 500 <<<<<** MORE TESTING PLEASE
- [x]  ImmersiOn-VRelia BlueSky Pro
- [x]  Deepoon VR M2 Pro
- [x]  Helmet Vision Fly
- [x]  Pico G2 4K
- [x]  HP Reverb
- [x]  Pimax 5K Plus
- [x]  Deepoon VR E3-C
- [x]  Deepoon VR E3-Polaris
- [x]  HTC Vive Pro
- [x]  Varjo VR-1
- [x]  Deepoon VR E3-B
- [x]  Oculus Rift
- [x]  Oculus Rift S
- [x]  Oculus Quest
- [x]  Shadow VR
- [x]  VR Shinecon
- [x]  Zeiss VR One
- [x]  Sytros Premium VR
- [x]  Bnext VR
- [x]  Google Daydream View
- [x]  VR JR BuD Da
- [x]  Pico Neo
- [x]  Mirage Solo
- [x]  Snapdragon VR820
- [x]  Deepoon VR P1
- [x]  HTC Vive
- [ ]  **FOVE <<<<** MORE TESTING PLEASE
- [x]  VIVE Focus
- [x]  LG Ultragear VR
- [x]  HP Reverb
- [x]  Pimax 5K Plus
- [x]  Sytros Premium VR
- [x]  Bnext VR
- [x]  Google Daydream View
- [x]  VR JR BuD Da
- [x]  Pico Neo
- [x]  VeeR Fabric VR
- [x]  VR Shinecon
- [x]  Zeiss VR One
- [x]  Sytros Premium VR
- [x]  Bnext VR
- [x]  Google Daydream View
- [x]  VR JR BuD Da
- [x]  Pico Neo
- [x]  Deepoon VR E3-C
- [x]  Deepoon VR E3-Polaris
- [x]  HTC Vive Pro
- [x]  Varjo VR-1
- [x]  VRHero 5K Plus

**Comment by shayypy** [comment]
I am 100% sure of the following working: 
> * [x]   Google Cardboard
> * [x]   Sytros Premium VR
> * [x]   Bnext VR
> * [x]   Google Daydream View
> * [x]   VR JR BuD Da
> * [x]   Pico Neo
> * [x]   VeeR Fabric VR
> * [x]   VR Shinecon
> * [x]   Zeiss VR One
> * [x]   Sytros Premium VR
> * [x]   Bnext VR
> * [x]   Google Daydream View
> * [x]   VR JR BuD Da
> * [x]   Pico Neo
> * [x]   Sytros Premium VR
> * [x]   Bnext VR
> * [x]   Google Daydream View
> * [x]   VR JR BuD Da
> * [x]   Pico Neo
> * [x]   VeeR Fabric VR
> * [x]   VR Shinecon
> * [x]   Zeiss VR One
> * [x]   Sytros Premium VR
> * [x]   Bnext VR
> * [x]   Google Daydream View
> * [x]   VR JR BuD Da
> * [x]   Pico Neo
> * [x]   VeeR Fabric VR
> * [x]   Merge
> * [x]   VeeR OASIS VR
> * [x]   VR Shinecon
> * [x]   Zeiss VR One
> * [x]   Sytros Premium VR
> * [x]   Bnext VR
> * [x]   Google Daydream View
> * [x]   VR JR BuD Da
> * [x]   Pico Neo
> * [x]   Pico Goblin
> * [x]   Sytros Premium VR
> * [x]   Bnext VR
> * [x]   Google Daydream View
> * [x]   VR JR BuD Da
> * [x]   Pico Neo
> * [x]   VeeR Fabric VR
> * [x]   VR Shinecon
> * [x]   Zeiss VR One
> * [x]   Sytros Premium VR
> * [x]   Bnext VR
> * [x]   Google Daydream View
> * [x]   VR JR BuD Da
> * [x]   Pico Neo
> * [x]   Playstation VR
> * [x]   Galax Vision
> * [x]   Huawei VR2
> * [x]   Acer AH101
> * [x]   Razer OSVR HDK 1
> * [x]   HP VR1000-100
> * [x]   HP Reverb
> * [x]   Pimax 5K Plus
> * [x]   Deepoon VR E3-C
> * [x]   Deepoon VR E3-Polaris
> * [x]   HTC Vive Pro
> * [x]   Varjo VR-1
> * [x]   Dell Visor
> * [x]   Lenovo Explorer
> * [x]   Helmet Vision Fly
> * [x]   Pico G2 4K
> * [x]   Deepoon VR E3-B
> * [x]   Oculus Rift
> * [x]   Oculus Rift S
> * [x]   Oculus Quest
> * [x]   Shadow VR
> * [x]   Mirage Solo
> * [x]   Snapdragon VR820
> * [x]   Helmet Vision Fly
> * [x]   Pico G2 4K
> * [x]   Deepoon VR E3-B
> * [x]   Oculus Rift
> * [x]   Deepoon VR M2 Pro
> * [x]   Helmet Vision Fly
> * [x]   Pico G2 4K
> * [x]   HP Reverb
> * [x]   Sytros Premium VR
> * [x]   Bnext VR
> * [x]   Google Daydream View
> * [x]   VR JR BuD Da
> * [x]   Pico Neo
> * [x]   VeeR Fabric VR
> * [x]   Pimax 5K Plus
> * [x]   Sytros Premium VR
> * [x]   Bnext VR
> * [x]   Google Daydream View
> * [x]   VR JR BuD Da
> * [x]   Pico Neo
> * [x]   VeeR Fabric VR
> * [x]   VR Shinecon
> * [x]   Zeiss VR One
> * [x]   Sytros Premium VR
> * [x]   Bnext VR
> * [x]   Google Daydream View
> * [x]   VR JR BuD Da
> * [x]   Pico Neo
> * [x]   Deepoon VR E3-C
> * [x]   Oculus Rift S
> * [x]   Oculus Quest
> * [x]   Shadow VR
> * [x]   Mirage Solo
> * [x]   Snapdragon VR820
> * [x]   Deepoon VR P1
> * [x]   Deepoon VR P1
> * [x]   Razer OSVR HDK 2
> * [x]   Acer OJO 500
> * [x]   ImmersiOn-VRelia BlueSky Pro
> * [x]   Deepoon VR M2 Pro
> * [x]   Helmet Vision Fly
> * [x]   Pico G2 4K
> * [x]   HP Reverb
> * [x]   Pimax 5K Plus
> * [x]   Deepoon VR E3-C
> * [x]   Deepoon VR E3-Polaris
> * [x]   HTC Vive Pro
> * [x]   Varjo VR-1
> * [x]   Deepoon VR E3-B
> * [x]   Oculus Rift
> * [x]   Oculus Rift S
> * [x]   Oculus Quest
> * [x]   Shadow VR
> * [x]   VR Shinecon
> * [x]   Zeiss VR One
> * [x]   Sytros Premium VR
> * [x]   Bnext VR
> * [x]   Google Daydream View
> * [x]   VR JR BuD Da
> * [x]   Pico Neo
> * [x]   Mirage Solo
> * [x]   Snapdragon VR820
> * [x]   Deepoon VR P1
> * [x]   HTC Vive
> * [x]   FOVE
> * [x]   VIVE Focus
> * [x]   LG Ultragear VR
> * [x]   HP Reverb
> * [x]   Pimax 5K Plus
> * [x]   Sytros Premium VR
> * [x]   Bnext VR
> * [x]   Google Daydream View
> * [x]   VR JR BuD Da
> * [x]   Pico Neo
> * [x]   VeeR Fabric VR
> * [x]   VR Shinecon
> * [x]   Zeiss VR One
> * [x]   Sytros Premium VR
> * [x]   Bnext VR
> * [x]   Google Daydream View
> * [x]   VR JR BuD Da
> * [x]   Pico Neo
> * [x]   Deepoon VR E3-C
> * [x]   Deepoon VR E3-Polaris
> * [x]   HTC Vive Pro
> * [x]   Varjo VR-1
> * [x]   VRHero 5K Plus

**Comment by pagoru** [comment]
Not suree, I need to ask to Microsoft Support first.

**Pull request closed without merging**
